version: 2

project_name: ffc

before:
  hooks:
    - go mod tidy

builds:
  - id: ffc
    main: ./cmd/ffc
    binary: ffc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/nasroykh/foxmayn_frappe_cli/internal/version.Version={{ .Version }}
      - -X github.com/nasroykh/foxmayn_frappe_cli/internal/version.Commit={{ .Commit }}
      - -X github.com/nasroykh/foxmayn_frappe_cli/internal/version.Date={{ .Date }}

archives:
  - id: ffc
    name_template: "ffc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
