package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/huh/spinner"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive setup wizard for ~/.config/ffc/config.yaml",
	Long: `Create or update the ffc configuration file interactively.

You will be prompted for your Frappe site URL and API credentials.
API keys can be generated at: User → API Access → Generate Keys.
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfgDir, err := defaultConfigDir()
		if err != nil {
			return fmt.Errorf("config dir: %w", err)
		}
		cfgPath := filepath.Join(cfgDir, "config.yaml")

		// Warn if a config already exists.
		var overwrite bool
		if _, err := os.Stat(cfgPath); err == nil {
			if err := huh.NewConfirm().
				Title(fmt.Sprintf("Config already exists at %s", cfgPath)).
				Description("Do you want to overwrite it?").
				Value(&overwrite).
				Run(); err != nil {
				return err
			}
			if !overwrite {
				fmt.Fprintln(os.Stderr, "Aborted. Existing config kept.")
				return nil
			}
		}

		// Collect site details.
		var (
			siteName  string
			siteURL   string
			apiKey    string
			apiSecret string
		)

		form := huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("Site name").
					Description("A short identifier, e.g. dev or production").
					Placeholder("dev").
					Validate(func(s string) error {
						s = strings.TrimSpace(s)
						if s == "" {
							return fmt.Errorf("site name cannot be empty")
						}
						if strings.ContainsAny(s, " \t") {
							return fmt.Errorf("site name must not contain spaces")
						}
						return nil
					}).
					Value(&siteName),

				huh.NewInput().
					Title("Site URL").
					Description("Base URL of your Frappe site").
					Placeholder("https://mysite.example.com").
					Validate(func(s string) error {
						s = strings.TrimSpace(s)
						if s == "" {
							return fmt.Errorf("URL cannot be empty")
						}
						if !strings.HasPrefix(s, "http://") && !strings.HasPrefix(s, "https://") {
							return fmt.Errorf("URL must start with http:// or https://")
						}
						return nil
					}).
					Value(&siteURL),
			),
			huh.NewGroup(
				huh.NewInput().
					Title("API Key").
					Description("From User → API Access → Generate Keys").
					Placeholder("21393a7e100ae26").
					Value(&apiKey),

				huh.NewInput().
					Title("API Secret").
					EchoMode(huh.EchoModePassword).
					Value(&apiSecret),
			),
		)

		if err := form.Run(); err != nil {
			return err
		}

		siteName = strings.TrimSpace(siteName)
		siteURL = strings.TrimRight(strings.TrimSpace(siteURL), "/")

		// Write config file with a spinner.
		var writeErr error
		_ = spinner.New().
			Title("Writing config...").
			Action(func() {
				writeErr = writeConfig(cfgPath, siteName, siteURL, apiKey, apiSecret)
			}).
			Run()

		if writeErr != nil {
			return fmt.Errorf("write config: %w", writeErr)
		}

		fmt.Fprintf(os.Stderr, "\n✓ Config written to %s\n", cfgPath)
		fmt.Fprintf(os.Stderr, "  Run: ffc --site %s list-docs --doctype Sales Invoice\n", siteName)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}

// writeConfig creates the config directory and writes a YAML config file.
func writeConfig(path, siteName, siteURL, apiKey, apiSecret string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	content := fmt.Sprintf(`# ffc configuration — generated by 'ffc init'
# Edit this file to add more sites.

default_site: %s

sites:
  %s:
    url: "%s"
    api_key: "%s"
    api_secret: "%s"
`,
		siteName,
		siteName,
		siteURL,
		apiKey,
		apiSecret,
	)

	return os.WriteFile(path, []byte(content), 0o600) // 0600: owner read/write only
}

// defaultConfigDir returns ~/.config/ffc — kept in sync with config package.
func defaultConfigDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "ffc"), nil
}
