// Command gendocs writes the shell completion scripts and man pages that the
// release archives ship. It is not shipped; GoReleaser runs it before the build.
//
//	go run ./tools/gendocs <dir> [version [unix-time]]
//
// It replaces <dir>/completions (ffc.bash, ffc.zsh, ffc.fish, ffc.ps1) and
// <dir>/manpages (one page per command, section 1). The pages are dated
// unix-time (GoReleaser passes the commit time, so a rebuild of a tag gives the
// same pages), else now.
package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/nasroykh/foxmayn_frappe_cli/internal/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) < 1 || len(args) > 3 {
		return errors.New("usage: gendocs <dir> [version [unix-time]]")
	}
	version, date := "dev", time.Now()
	if len(args) >= 2 {
		version = strings.TrimPrefix(args[1], "v")
	}
	if len(args) == 3 {
		sec, err := strconv.ParseInt(args[2], 10, 64)
		if err != nil || sec <= 0 {
			return fmt.Errorf("bad unix time %q", args[2])
		}
		date = time.Unix(sec, 0).UTC()
	}
	root := cmd.Root()
	root.DisableAutoGenTag = true // no "Auto generated by spf13/cobra on <date>" footer
	if err := completions(root, filepath.Join(args[0], "completions")); err != nil {
		return fmt.Errorf("completions: %w", err)
	}
	if err := manpages(root, filepath.Join(args[0], "manpages"), version, date); err != nil {
		return fmt.Errorf("man pages: %w", err)
	}
	return nil
}

func completions(root *cobra.Command, dir string) error {
	if err := freshDir(dir); err != nil {
		return err
	}
	scripts := []struct {
		name string
		gen  func(string) error
	}{
		{"ffc.bash", func(p string) error { return root.GenBashCompletionFileV2(p, true) }},
		{"ffc.zsh", root.GenZshCompletionFile},
		{"ffc.fish", func(p string) error { return root.GenFishCompletionFile(p, true) }},
		{"ffc.ps1", root.GenPowerShellCompletionFileWithDesc},
	}
	for _, s := range scripts {
		if err := s.gen(filepath.Join(dir, s.name)); err != nil {
			return err
		}
	}
	return nil
}

func manpages(root *cobra.Command, dir, version string, date time.Time) error {
	if err := freshDir(dir); err != nil {
		return err
	}
	header := &doc.GenManHeader{
		Title:   "FFC",
		Section: "1",
		Source:  "ffc " + version,
		Manual:  "Foxmayn Frappe CLI",
		Date:    &date,
	}
	return doc.GenManTree(root, header, dir)
}

// freshDir empties dir, so a page for a removed command never lingers.
func freshDir(dir string) error {
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	return os.MkdirAll(dir, 0o755)
}
