// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService reports the environment, installs ffc and opens things with
 * the operating system.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Environment returns the app and ffc versions, the config path and the
 * WSL detection (run once per app start).
 */
export function Environment(): $CancellablePromise<$models.Environment> {
    return $Call.ByID(991364871);
}

/**
 * InstallFFC downloads the latest ffc release from GitHub, verifies its
 * signature and checksum, installs it for this user (see ffcInstaller), sends
 * each step as an "installer:log" event, then looks for the binary again.
 * The UI asks the user first. Cancelling the call stops the download.
 */
export function InstallFFC(): $CancellablePromise<$models.FFCInfo> {
    return $Call.ByID(2608237942);
}

/**
 * OpenConfigFolder opens the folder that holds config.yaml.
 */
export function OpenConfigFolder(): $CancellablePromise<void> {
    return $Call.ByID(2189846200);
}

/**
 * OpenFFCFolder opens the folder that holds the ffc binary.
 */
export function OpenFFCFolder(): $CancellablePromise<void> {
    return $Call.ByID(3363306067);
}

/**
 * OpenWebsite opens an http(s) URL in the default browser.
 */
export function OpenWebsite(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(3360346479, rawURL);
}

/**
 * RefreshFFC looks for the ffc binary again.
 */
export function RefreshFFC(): $CancellablePromise<$models.FFCInfo> {
    return $Call.ByID(3479642558);
}
