// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssistantsService connects AI clients to ffc: it adds, updates or removes
 * the MCP server entry that runs "ffc mcp" in each client's user config,
 * through internal/mcpinstall (the same code as "ffc mcp install").
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect adds or updates the entry. The old config file is kept as
 * <file>.ffc-<stamp>.bak.
 */
export function Connect(req: $models.ConnectRequest): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(400861586, req);
}

/**
 * Disconnect removes the entry from the client's config.
 */
export function Disconnect(client: string): $CancellablePromise<$models.ApplyResult> {
    return $Call.ByID(3816555414, client);
}

/**
 * List returns every client with its connection state.
 */
export function List(): $CancellablePromise<$models.AssistantList> {
    return $Call.ByID(4274998820);
}

/**
 * Preview shows what Connect would change, without changing anything.
 */
export function Preview(req: $models.ConnectRequest): $CancellablePromise<$models.Preview> {
    return $Call.ByID(2883728376, req);
}

/**
 * PreviewDisconnect shows what Disconnect would change.
 */
export function PreviewDisconnect(client: string): $CancellablePromise<$models.Preview> {
    return $Call.ByID(699575890, client);
}
