// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssistantService is the chat assistant: conversations, runs, approvals and
 * providers. Provider keys stay in Go: they go to the OS keychain and to the
 * provider's API, never to the web view, events, the store or error text.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer settles an approval card of a conversation.
 */
export function Answer(convID: string, approvalID: string, approve: boolean): $CancellablePromise<void> {
    return $Call.ByID(1126072435, convID, approvalID, approve);
}

/**
 * Cancel stops a run. A card that is open counts as declined.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2711272351, runID);
}

/**
 * Continue resumes a paused run with a fresh step budget.
 */
export function Continue(runID: string): $CancellablePromise<void> {
    return $Call.ByID(73196768, runID);
}

/**
 * DeleteConversation removes a conversation and everything in it. A
 * conversation with a run in progress cannot be deleted.
 */
export function DeleteConversation(id: string): $CancellablePromise<void> {
    return $Call.ByID(967471485, id);
}

/**
 * DeleteProvider removes a provider and its key.
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(2881373875, id);
}

/**
 * DetectLocal looks for Ollama and LM Studio on this computer. It saves
 * nothing: SaveProvider adds one.
 */
export function DetectLocal(): $CancellablePromise<$models.ProviderInfo[] | null> {
    return $Call.ByID(4293306125);
}

/**
 * GetConversation returns a conversation with its messages in the shape the
 * chat shows. The model's thinking and its signatures never leave Go.
 */
export function GetConversation(id: string): $CancellablePromise<$models.ConversationDetail> {
    return $Call.ByID(3781995916, id);
}

/**
 * KeyStatus says whether a provider has a key, and its last four characters.
 */
export function KeyStatus(providerID: string): $CancellablePromise<$models.KeyStatus> {
    return $Call.ByID(2390213962, providerID);
}

/**
 * ListConversations returns every conversation, most recent first.
 */
export function ListConversations(): $CancellablePromise<$models.Conversation[] | null> {
    return $Call.ByID(912901527);
}

/**
 * ListModels lists the models a provider offers.
 */
export function ListModels(providerID: string): $CancellablePromise<$models.Model[] | null> {
    return $Call.ByID(920098499, providerID);
}

/**
 * ListProviders returns the saved providers, with whether each has a key.
 */
export function ListProviders(): $CancellablePromise<$models.ProviderInfo[] | null> {
    return $Call.ByID(427171861);
}

/**
 * NewConversation starts a conversation on a site. mode is "read" (the
 * default) or "ask"; an empty model means the provider's default.
 */
export function NewConversation(site: string, mode: string, providerID: string, model: string): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(2244419614, site, mode, providerID, model);
}

/**
 * PendingApprovals lists the open cards of a conversation, so the UI can show
 * them again after a reload.
 */
export function PendingApprovals(convID: string): $CancellablePromise<$models.ChatApproval[] | null> {
    return $Call.ByID(3114282216, convID);
}

/**
 * SaveProvider adds or changes a provider. An empty ID takes the kind's name
 * (a custom provider gets a numbered one). The key is set apart, with SetKey.
 * Anthropic and OpenRouter are pinned to their own hosts. When a provider's
 * address changes the stored key is deleted in the same step (KeyCleared), so
 * a key can never be sent to a host the user did not give it to.
 */
export function SaveProvider(p: $models.ProviderInfo): $CancellablePromise<$models.ProviderInfo> {
    return $Call.ByID(1471689505, p);
}

/**
 * Send adds the user's message to a conversation and starts a run. It returns
 * the run's id at once; the answer arrives as chat:* events.
 */
export function Send(convID: string, text: string): $CancellablePromise<string> {
    return $Call.ByID(2635608883, convID, text);
}

/**
 * SetConversationMode switches a conversation between "read" (read only) and
 * "ask" (ask before changes). It is refused while a run is active.
 */
export function SetConversationMode(id: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(2760257883, id, mode);
}

/**
 * SetKey checks a key against the provider and saves it in the OS keychain
 * only when the provider accepts it. A key the provider refuses is CodeAuth;
 * any other failure to check (timeout, network, server error) is CodeNetwork.
 * Either way nothing is saved and the earlier key stays.
 */
export function SetKey(providerID: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(313735678, providerID, key);
}
