// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssistantService is the chat assistant: conversations, runs, approvals and
 * providers. Provider keys stay in Go: they go to the OS keychain and to the
 * provider's API, never to the web view, events, the store or error text.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer settles an approval card of a conversation.
 */
export function Answer(convID: string, approvalID: string, approve: boolean): $CancellablePromise<void> {
    return $Call.ByID(1126072435, convID, approvalID, approve);
}

/**
 * Archive moves a conversation to the archive or back. Searching leaves the
 * archive out unless asked for it. It does not change the conversation's
 * updated time.
 */
export function Archive(convID: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(3227966633, convID, archived);
}

/**
 * Cancel stops a run. A card that is open counts as declined.
 */
export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2711272351, runID);
}

/**
 * CancelSignIn stops the OpenRouter sign-in in progress, if any.
 */
export function CancelSignIn(): $CancellablePromise<void> {
    return $Call.ByID(2033421221);
}

/**
 * Continue resumes a paused run with a fresh step budget.
 */
export function Continue(runID: string): $CancellablePromise<void> {
    return $Call.ByID(73196768, runID);
}

/**
 * DeleteConversation removes a conversation and everything in it. A
 * conversation with a run in progress cannot be deleted.
 */
export function DeleteConversation(id: string): $CancellablePromise<void> {
    return $Call.ByID(967471485, id);
}

/**
 * DeleteProfile removes one of the user's profiles. Its conversations move to
 * the Explore preset (read only), so nothing gains rights. It is refused
 * while one of them has a run in progress.
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(174510683, id);
}

/**
 * DeleteProvider removes a provider and its key.
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(2881373875, id);
}

/**
 * DetectLocal looks for Ollama and LM Studio on this computer. It saves
 * nothing: SaveProvider adds one.
 */
export function DetectLocal(): $CancellablePromise<$models.ProviderInfo[] | null> {
    return $Call.ByID(4293306125);
}

/**
 * ExportConversation saves a conversation to a file the person chooses.
 * format is "json" (everything, to import again) or "md" (to read). It
 * returns the path, or "" when the person cancelled. The file
 * holds no provider key.
 */
export function ExportConversation(convID: string, format: string): $CancellablePromise<string> {
    return $Call.ByID(4119506776, convID, format);
}

/**
 * GetConversation returns a conversation with its messages in the shape the
 * chat shows. The model's thinking and its signatures never leave Go.
 */
export function GetConversation(id: string): $CancellablePromise<$models.ConversationDetail> {
    return $Call.ByID(3781995916, id);
}

/**
 * GetRetention returns how many days a conversation is kept after its last
 * message: 0 (forever), 90 or 30. Pinned conversations and conversations
 * with a run in progress are always kept.
 */
export function GetRetention(): $CancellablePromise<number> {
    return $Call.ByID(1233478011);
}

/**
 * GetSiteSettings returns the settings that apply to a site of the ffc
 * config.
 */
export function GetSiteSettings(site: string): $CancellablePromise<$models.SiteSettings> {
    return $Call.ByID(403689253, site);
}

/**
 * ImportConversation reads a conversation file (made by ExportConversation)
 * the person chooses and adds it as a new conversation, read only, with new
 * ids. Images are not in the file and become notes. A file over 50 MB, of
 * another format or version, or that does not hold together is refused.
 */
export function ImportConversation(): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1284281039);
}

/**
 * KeyStatus says whether a provider has a key, and its last four characters.
 */
export function KeyStatus(providerID: string): $CancellablePromise<$models.KeyStatus> {
    return $Call.ByID(2390213962, providerID);
}

/**
 * ListConversations returns every conversation, most recent first.
 */
export function ListConversations(): $CancellablePromise<$models.Conversation[] | null> {
    return $Call.ByID(912901527);
}

/**
 * ListModels lists the models a provider offers.
 */
export function ListModels(providerID: string): $CancellablePromise<$models.Model[] | null> {
    return $Call.ByID(920098499, providerID);
}

/**
 * ListPresets returns the built-in profiles.
 */
export function ListPresets(): $CancellablePromise<$models.Profile[] | null> {
    return $Call.ByID(558624303);
}

/**
 * ListProfiles returns the user's own profiles, by name.
 */
export function ListProfiles(): $CancellablePromise<$models.Profile[] | null> {
    return $Call.ByID(2795292991);
}

/**
 * ListProviders returns the saved providers, with whether each has a key.
 */
export function ListProviders(): $CancellablePromise<$models.ProviderInfo[] | null> {
    return $Call.ByID(427171861);
}

/**
 * NewConversation starts a conversation on a site. mode is "read" (the
 * default) or "ask"; an empty model means the provider's default.
 */
export function NewConversation(site: string, mode: string, providerID: string, model: string): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(2244419614, site, mode, providerID, model);
}

/**
 * PendingApprovals lists the open cards of a conversation, so the UI can show
 * them again after a reload.
 */
export function PendingApprovals(convID: string): $CancellablePromise<$models.ChatApproval[] | null> {
    return $Call.ByID(3114282216, convID);
}

/**
 * Pin pins or unpins a conversation. It does not change the conversation's
 * updated time.
 */
export function Pin(convID: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(4270282480, convID, pinned);
}

/**
 * PromptPreview builds the next run's prompt of a conversation the way the
 * run does. It opens an engine session (which may sign in to the site) but
 * calls no tool: the site context shown is the one stored.
 */
export function PromptPreview(convID: string): $CancellablePromise<$models.PromptPreview> {
    return $Call.ByID(1803562521, convID);
}

/**
 * Rename sets the title of a conversation. A title the user chose is kept: no
 * automatic title replaces it.
 */
export function Rename(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2992165439, id, title);
}

/**
 * SaveProfile adds (empty ID) or changes one of the user's profiles. Presets
 * cannot be changed: save a copy with BasedOn set to the preset.
 */
export function SaveProfile(p: $models.Profile): $CancellablePromise<$models.Profile> {
    return $Call.ByID(2901857345, p);
}

/**
 * SaveProvider adds or changes a provider. An empty ID takes the kind's name
 * (a custom provider gets a numbered one). The key is set apart, with SetKey.
 * Anthropic, OpenRouter, OpenAI and Gemini are pinned to their own hosts
 * (stored as an empty address, except OpenRouter's). When a provider's
 * address changes the stored key is deleted in the same step (KeyCleared), so
 * a key can never be sent to a host the user did not give it to.
 */
export function SaveProvider(p: $models.ProviderInfo): $CancellablePromise<$models.ProviderInfo> {
    return $Call.ByID(1471689505, p);
}

/**
 * SaveSiteSettings saves a site's instructions and its local-only switch. The
 * address is taken from the ffc config, never from the caller. Turning
 * local-only off also turns it off in settings saved under an earlier name
 * of the site (same address, no longer in the ffc config), which would
 * otherwise keep it on. Another configured site with the same address keeps
 * its own setting.
 */
export function SaveSiteSettings(s: $models.SiteSettings): $CancellablePromise<$models.SiteSettings> {
    return $Call.ByID(1529594082, s);
}

/**
 * Search finds messages by their words, best match first, in the
 * conversations that are not archived (or only in the archived ones). limit
 * is the most hits returned: 0 means 50, at most 200.
 */
export function Search(query: string, filter: $models.SearchFilter, limit: number): $CancellablePromise<$models.SearchHit[] | null> {
    return $Call.ByID(1284597821, query, filter, limit);
}

/**
 * Send adds the user's message to a conversation and starts a run. It returns
 * the run's id at once; the answer arrives as chat:* events.
 */
export function Send(convID: string, text: string): $CancellablePromise<string> {
    return $Call.ByID(2635608883, convID, text);
}

/**
 * SetConversationMode switches a conversation between "read" (read only) and
 * "ask" (ask before changes). It is refused while a run is active.
 */
export function SetConversationMode(id: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(2760257883, id, mode);
}

/**
 * SetConversationProfile gives a conversation a profile ("" for none). When
 * the profile names a provider the conversation switches to it, and a site
 * set to local models only refuses a provider that is not local. It is
 * refused while a run is active.
 */
export function SetConversationProfile(convID: string, profileID: string): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(4043675533, convID, profileID);
}

/**
 * SetKey checks a key against the provider and saves it in the OS keychain
 * only when the provider accepts it. A key the provider refuses is CodeAuth;
 * any other failure to check (timeout, network, server error) is CodeNetwork.
 * Either way nothing is saved and the earlier key stays.
 */
export function SetKey(providerID: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(313735678, providerID, key);
}

/**
 * SetRetention sets the retention period: 0 (forever), 90 or 30 days. Older
 * conversations are deleted when the app starts and then once a day, not at
 * once.
 */
export function SetRetention(days: number): $CancellablePromise<void> {
    return $Call.ByID(1350140959, days);
}

/**
 * SignInOpenRouter gets an OpenRouter key through the browser (OAuth PKCE):
 * it opens OpenRouter's sign-in page, waits for the redirect to a local
 * callback (at most 5 minutes), trades the code for a key, checks the key
 * like SetKey and saves it in the OS keychain. The key goes nowhere else:
 * the result and the "auth:openrouter" events carry the status only, tagged
 * with attempt (the caller's id for this try, so it can drop the events of
 * one it gave up on). A new call replaces a sign-in in progress. The
 * provider must exist and be of kind openrouter.
 * 
 * Cancel and save: CancelSignIn, cancelling the call, a newer sign-in or
 * the service shutting down stop the attempt up to the code exchange.
 * Once the exchange has answered with a key, the key exists on the user's
 * OpenRouter account either way, so the attempt no longer stops: the check
 * and the save finish (bounded by saveAfterExchange) and it ends "done", or
 * "failed" when the key is refused. Shutdown waits for that through the
 * in-flight call (enter).
 */
export function SignInOpenRouter(providerID: string, attempt: string): $CancellablePromise<$models.ProviderInfo> {
    return $Call.ByID(4028737366, providerID, attempt);
}
