// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * APIKeyRequest adds a site with an API key and secret.
 */
export interface APIKeyRequest {
    "name": string;
    "url": string;
    "apiKey": string;
    "apiSecret": string;

    /**
     * Replace an existing site of the same name.
     */
    "replace": boolean;
}

/**
 * AddedSite is the site an Add call saved.
 */
export interface AddedSite {
    "name": string;
    "url": string;
    "auth": string;
    "user": string;
    "isDefault": boolean;

    /**
     * Replaced: an existing site of this name was replaced.
     */
    "replaced": boolean;

    /**
     * Registered (OAuth): the app registered its own OAuth Client.
     */
    "registered": boolean;
}

/**
 * ApplyResult is the outcome of Connect or Disconnect.
 */
export interface ApplyResult {
    "changed": boolean;

    /**
     * Backup is the copy of the old config file ("" when there was none).
     */
    "backup": string;
    "hint": string;
}

/**
 * Assistant is one AI client and its connection to ffc.
 */
export interface Assistant {
    "id": string;
    "name": string;

    /**
     * Detected: the client looks installed. Claude Code: the claude CLI is
     * on PATH (it is what the app runs). The others: the folder of their
     * user config exists (Claude Desktop, VS Code and Codex create it on
     * first start, Cursor its ~/.cursor folder). A client that was never
     * started counts as not detected; connecting still works for those.
     */
    "detected": boolean;
    "status": string;

    /**
     * Site and ReadOnly are the settings of a connected entry: Site "" is
     * "follow the default site".
     */
    "site": string;
    "readOnly": boolean;

    /**
     * ConfigPath is the client's config file (Claude Code: its state file,
     * which only the claude CLI writes).
     */
    "configPath": string;
    "hint": string;
    "error"?: string;
}

/**
 * AssistantList is every supported client.
 */
export interface AssistantList {
    "ffc": FFCInfo;
    "entryName": string;
    "assistants": Assistant[] | null;
}

/**
 * BrowserSignInRequest adds a site through the OAuth browser sign-in.
 */
export interface BrowserSignInRequest {
    "name": string;
    "url": string;

    /**
     * ClientID and ClientSecret name an OAuth Client created on the site by
     * hand (the CLI's --client-id and FFC_OAUTH_CLIENT_SECRET). Empty: the
     * app registers one when the site allows it.
     */
    "clientID": string;
    "clientSecret": string;
    "replace": boolean;

    /**
     * Attempt is an ID the UI picks for this sign-in; every progress event
     * of it carries the same ID.
     */
    "attempt": string;
}

/**
 * ChatApproval is the payload of EventChatApproval and an item of the list
 * the UI reads to show open cards again after a reload.
 */
export interface ChatApproval {
    "runID": string;
    "approvalID": string;

    /**
     * Kind is "app" (the app's card) or "ffc" (ffc's own confirmation).
     */
    "kind": string;
    "tool": string;
    "site": string;
    "doctypes"?: string[] | null;
    "names"?: string[] | null;

    /**
     * Args is the exact JSON the call will run with.
     */
    "args": json$0.RawMessage;

    /**
     * Diff lists the changed fields of an update_doc.
     */
    "diff"?: DiffField[] | null;

    /**
     * NoChanges is set for an update_doc whose data matches the document
     * already, so the UI can say "no field changes".
     */
    "noChanges"?: boolean;

    /**
     * Message is ffc's question, for kind "ffc".
     */
    "message"?: string;
}

/**
 * ChatApprovalClosed is the payload of EventChatApprovalClosed. Outcome is
 * "approved", "declined" or "cancelled".
 */
export interface ChatApprovalClosed {
    "runID": string;
    "approvalID": string;
    "outcome": string;
}

/**
 * ChatDelta is the payload of EventChatDelta.
 */
export interface ChatDelta {
    "runID": string;
    "text": string;
}

/**
 * ChatDone is the payload of EventChatDone.
 */
export interface ChatDone {
    "runID": string;
    "status": string;

    /**
     * StopReason is set when the model ended the run for a reason the user
     * should hear of: "max_tokens" or "refusal".
     */
    "stopReason"?: string;

    /**
     * Category is the policy area of a refusal, when the provider gave one.
     */
    "category"?: string;
}

/**
 * ChatError is the payload of EventChatError.
 */
export interface ChatError {
    "runID": string;
    "error": Error | null;
}

/**
 * ChatMessage is one visible message. Tool results and the model's thinking
 * are not shown.
 */
export interface ChatMessage {
    "id": string;

    /**
     * Role is "user" or "assistant".
     */
    "role": string;
    "text": string;
    "tools": ChatToolCall[] | null;
    "created": string;
}

/**
 * ChatTool is the payload of EventChatTool.
 */
export interface ChatTool {
    "runID": string;
    "callID": string;
    "tool": string;
    "site": string;
    "status": string;
    "summary": string;
}

/**
 * ChatToolCall is a tool call of an assistant message, as the chat shows it.
 */
export interface ChatToolCall {
    /**
     * ID is the callID of chat:tool events.
     */
    "id": string;
    "tool": string;
    "site": string;

    /**
     * Status is "running", "ok", "error" or "stopped".
     */
    "status": string;

    /**
     * Approval is "", "approved", "declined", "cancelled", "ffc-approved" or
     * "ffc-declined".
     */
    "approval": string;
    "summary": string;
}

/**
 * ChatUsage is the payload of EventChatUsage.
 */
export interface ChatUsage {
    "runID": string;
    "turn": number;
    "input": number;
    "output": number;
    "cached": number;
}

/**
 * CheckResult is the outcome of a connection check.
 */
export interface CheckResult {
    "ok": boolean;

    /**
     * User is who the site says is signed in ("" when it does not say, or
     * for a username/password site, where Frappe does not answer it).
     */
    "user": string;
    "message": string;
    "code"?: string;
    "checkedAt": string;
}

/**
 * ConfigChanged is the payload of EventConfigChanged.
 */
export interface ConfigChanged {
    "path": string;
    "exists": boolean;
}

/**
 * ConnectRequest says how to connect a client.
 */
export interface ConnectRequest {
    "client": string;

    /**
     * Site pins one site; "" follows the default site.
     */
    "site": string;
    "readOnly": boolean;
}

/**
 * Conversation is a chat thread bound to a site, a write mode, a provider and
 * a model.
 */
export interface Conversation {
    "id": string;
    "title": string;
    "site": string;
    "mode": string;
    "providerID": string;
    "model": string;
    "created": string;
    "updated": string;
}

/**
 * ConversationDetail is a conversation with its messages.
 */
export interface ConversationDetail {
    "conversation": Conversation;
    "messages": ChatMessage[] | null;

    /**
     * ActiveRunID is the run answering now, if any.
     */
    "activeRunID": string;

    /**
     * PausedRunID is the run waiting for Continue, if any.
     */
    "pausedRunID": string;
}

/**
 * DiffField is one changed field of an update_doc card.
 */
export interface DiffField {
    "field": string;
    "old": any;
    "new": any;
}

/**
 * Environment describes the machine the app runs on.
 */
export interface Environment {
    "appVersion": string;

    /**
     * OS is runtime.GOOS: "windows" or "darwin" (Linux is not a target yet).
     */
    "os": string;
    "configPath": string;
    "configExists": boolean;
    "ffc": FFCInfo;

    /**
     * InstallCommand installs ffc by hand: the README's one-liner, with the
     * script pinned to a release tag.
     */
    "installCommand": string;
    "wsl": WSLInfo;
}

/**
 * Error is an error the UI shows and acts on. Wails marshals it as the
 * call's "cause", so the frontend reads code, message and the rest.
 */
export interface Error {
    "code": string;
    "message": string;

    /**
     * Detail is the underlying error text, for a "details" disclosure.
     */
    "detail"?: string;

    /**
     * Field is the input the error is about ("name", "url", ...).
     */
    "field"?: string;

    /**
     * Unsupported (no_registration): the site does not offer registration
     * at all, as opposed to a failed attempt.
     */
    "unsupported"?: boolean;

    /**
     * RedirectURI (no_registration): the callback to register on a manual
     * OAuth Client.
     */
    "redirectURI"?: string;
}

/**
 * FFCInfo says whether the ffc binary is installed and where.
 */
export interface FFCInfo {
    "found": boolean;
    "path": string;
    "version": string;

    /**
     * Error is set when the binary was found but did not answer
     * "ffc --version".
     */
    "error"?: string;

    /**
     * Updatable means installing replaces this binary where it is: a working
     * release build (not "dev") whose file is ffc.exe on Windows, or ffc
     * after symlinks elsewhere, that no package manager owns. Otherwise an
     * install puts a new copy in the installer's own folder.
     */
    "updatable": boolean;

    /**
     * Manager names the package manager that installed this ffc (Homebrew,
     * Scoop, winget) and UpgradeCommand the command that updates it. The app
     * never installs over such a copy, nor next to it.
     */
    "manager"?: string;
    "upgradeCommand"?: string;
}

/**
 * FFCUpdate says whether a newer ffc release than the installed one exists.
 * InstallFFC installs it.
 */
export interface FFCUpdate {
    "available": boolean;

    /**
     * Current is the installed ffc's version ("" when ffc is not installed).
     */
    "current": string;

    /**
     * Latest is the newest ffc release ("" when none was found or the
     * installed ffc is not updatable: not a release build, or a file the app
     * must not replace).
     */
    "latest": string;
}

/**
 * InstallerLine is the payload of EventInstallerLog.
 */
export interface InstallerLine {
    "line": string;
}

/**
 * KeyStatus says whether a provider has a key. It never carries the key.
 */
export interface KeyStatus {
    "set": boolean;

    /**
     * Last4 is the last four characters of the key, only for keys of at
     * least 12 characters.
     */
    "last4"?: string;
}

/**
 * Model is one model a provider offers.
 */
export interface Model {
    "id": string;
    "label": string;

    /**
     * Default marks the model the app picks first.
     */
    "default": boolean;
}

/**
 * PasswordRequest adds a site with a username (or email) and password.
 */
export interface PasswordRequest {
    "name": string;
    "url": string;
    "username": string;
    "password": string;
    "replace": boolean;
}

/**
 * Preview is what connecting (or disconnecting) would change.
 */
export interface Preview {
    "client": string;
    "entryName": string;
    "path": string;

    /**
     * Changed: false when the entry is already exactly like this.
     */
    "changed": boolean;
    "replaces": boolean;

    /**
     * CreatesFile: the config file does not exist yet.
     */
    "createsFile": boolean;

    /**
     * Diff is the unified diff of the config file ("" for Claude Code).
     */
    "diff": string;

    /**
     * Commands are the claude CLI commands (Claude Code only).
     */
    "commands": string[] | null;

    /**
     * Server is the entry's command line.
     */
    "server": string[] | null;

    /**
     * CanApply is false when the change cannot be made here; Problem says
     * why (claude CLI missing, read-only file).
     */
    "canApply": boolean;
    "problem"?: string;
    "hint": string;
}

/**
 * ProviderInfo is a provider as the UI sees it. It never carries the key.
 */
export interface ProviderInfo {
    "id": string;
    "kind": string;
    "label": string;

    /**
     * BaseURL is empty for Anthropic's own API.
     */
    "baseURL": string;
    "defaultModel": string;
    "keySet": boolean;

    /**
     * KeyLast4 is the last four characters of a long enough key.
     */
    "keyLast4"?: string;

    /**
     * KeyCleared is set by SaveProvider when the stored key was deleted
     * because the provider's address changed: ask for the key again.
     */
    "keyCleared"?: boolean;
}

/**
 * RemoveResult is what removing a site did besides deleting it.
 */
export interface RemoveResult {
    /**
     * Revoked: the site's OAuth token was revoked on the server.
     */
    "revoked": boolean;

    /**
     * RevokeError is set when revoking failed; the site was removed anyway
     * and its token stays valid until it expires or is revoked by hand.
     */
    "revokeError"?: string;
    "wasDefault": boolean;
    "newDefault": string;
}

/**
 * SignInProgress is the payload of EventSignInProgress.
 */
export interface SignInProgress {
    /**
     * Attempt is BrowserSignInRequest.Attempt of the sign-in it belongs to.
     */
    "attempt"?: string;

    /**
     * Step is one of "starting", "registering", "browser", "finishing",
     * "saving", "done".
     */
    "step": string;

    /**
     * Message says what happens, for people.
     */
    "message": string;

    /**
     * AuthURL is the site's authorization page (step "browser"), so the UI
     * can offer to copy it when the browser did not open. It carries no
     * secret: the PKCE verifier stays in Go.
     */
    "authURL"?: string;

    /**
     * BrowserError is set when the browser could not be opened.
     */
    "browserError"?: string;
}

/**
 * Site is one configured site as the UI shows it: never a secret.
 */
export interface Site {
    "name": string;
    "url": string;
    "auth": string;
    "isDefault": boolean;

    /**
     * PlainHTTP: the URL is http://, so credentials travel unencrypted.
     */
    "plainHTTP": boolean;

    /**
     * Username is the stored login of a username/password site (not the
     * password). Empty for other methods.
     */
    "username"?: string;

    /**
     * LastCheck is the result of the last connection check in this run.
     */
    "lastCheck"?: CheckResult | null;
}

/**
 * SiteList is the config's sites, sorted by name.
 */
export interface SiteList {
    "configPath": string;
    "configExists": boolean;
    "defaultSite": string;
    "sites": Site[] | null;
}

/**
 * UpdateInfo is the answer of CheckForUpdate.
 */
export interface UpdateInfo {
    "available": boolean;

    /**
     * Current is the running version (AppVersion).
     */
    "current": string;

    /**
     * Latest is the newest version the app may offer ("" when none was found).
     */
    "latest": string;

    /**
     * URL is the release page on GitHub, always under this repository's
     * releases.
     */
    "url": string;

    /**
     * PublishedAt is the release's publish time (RFC 3339), or "".
     */
    "publishedAt": string;

    /**
     * InstallCommand installs Latest from a terminal (desktopInstallCommand),
     * set when an update is available and Latest has no prerelease suffix.
     */
    "installCommand": string;

    /**
     * FFC compares the installed ffc with the newest ffc release.
     */
    "ffc": FFCUpdate;
}

/**
 * Validation is the check of a name and URL as typed in step 1 of the Add
 * site form. Errors are per field; it never fails as a call.
 */
export interface Validation {
    "name": string;
    "url": string;
    "nameError"?: string;
    "urlError"?: string;

    /**
     * Exists: a site with this name is configured already.
     */
    "exists": boolean;
    "plainHTTP": boolean;
    "ok": boolean;
}

/**
 * WSLInfo reports ffc configs inside WSL distributions (Windows only). The
 * app manages the Windows config; a config in WSL belongs to the ffc
 * installed there and is not synced.
 */
export interface WSLInfo {
    "detected": boolean;
    "distros": string[] | null;

    /**
     * Paths are the config files found, as Windows paths
     * (\\wsl.localhost\<distro>\home\<user>\.config\ffc\config.yaml).
     */
    "paths": string[] | null;
}
