// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SitesService manages the sites in the ffc config file. Every write goes
 * through sitesetup.Store (config.Edit or config.Overwrite: lock, re-read,
 * atomic write), except the OAuth token refresh before a check, which uses
 * config.Edit the way the CLI does.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddWithAPIKey checks an API key and secret against the site and saves it.
 */
export function AddWithAPIKey(req: $models.APIKeyRequest): $CancellablePromise<$models.AddedSite> {
    return $Call.ByID(1621850583, req);
}

/**
 * AddWithPassword checks a username and password by logging in (and out
 * again) and saves them. Frappe accounts with two-factor sign-in cannot use
 * this method.
 */
export function AddWithPassword(req: $models.PasswordRequest): $CancellablePromise<$models.AddedSite> {
    return $Call.ByID(3924584497, req);
}

/**
 * CancelSignIn stops the browser sign-in in progress, if any.
 */
export function CancelSignIn(): $CancellablePromise<void> {
    return $Call.ByID(2433301437);
}

/**
 * ChangeURL points a site at a new address after checking its stored
 * credentials there. OAuth sites are refused: their OAuth client and tokens
 * belong to the old server, so they sign in again instead (as in the CLI).
 */
export function ChangeURL(name: string, rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(3021472746, name, rawURL);
}

/**
 * Check tests a site's stored credentials. An expired OAuth token is
 * refreshed first and the new token saved, as ffc does before talking to a
 * site. The result is remembered for List until the app quits.
 */
export function Check(name: string): $CancellablePromise<$models.CheckResult> {
    return $Call.ByID(3516102603, name);
}

/**
 * List returns the configured sites.
 */
export function List(): $CancellablePromise<$models.SiteList> {
    return $Call.ByID(3146350181);
}

/**
 * Remove deletes a site. An OAuth site's token is revoked on the server
 * first, at most revokeTimeout, before the config lock is taken; a failed
 * revocation is reported but does not stop the removal (as in the CLI).
 */
export function Remove(name: string): $CancellablePromise<$models.RemoveResult> {
    return $Call.ByID(4058840745, name);
}

/**
 * Rename renames a site. The default follows it; an assistant pinned to the
 * old name must be connected again.
 */
export function Rename(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(839178359, oldName, newName);
}

/**
 * ReopenSignInPage opens the sign-in page of the sign-in in progress again,
 * for when the browser tab was closed or did not open.
 */
export function ReopenSignInPage(): $CancellablePromise<void> {
    return $Call.ByID(1612784637);
}

/**
 * SetDefault makes a site the default (what ffc and "follow my default"
 * assistants use).
 */
export function SetDefault(name: string): $CancellablePromise<void> {
    return $Call.ByID(1022869880, name);
}

/**
 * SignInWithBrowser adds a site through the OAuth browser sign-in: it binds
 * the local callback, finds or registers the OAuth client, opens the site's
 * sign-in page in the browser, waits for the user (at most 5 minutes), and
 * saves the site with its tokens. Progress goes out as "signin:progress"
 * events tagged with req.Attempt, so the UI can drop events of an attempt it
 * has given up on. CancelSignIn, or cancelling the call, stops it. Each call
 * is a new flow, so a retry after a failure starts clean; a call made while
 * another sign-in runs cancels it and waits (at most replaceWait) for it to
 * close its callback server, so the new flow gets the same port and a
 * redirect URI registered on a hand-made client still matches.
 * 
 * When the site cannot register a client (Frappe v15, or registration
 * turned off), the error has code "no_registration" and the redirect URI to
 * register on a client created by hand; the UI asks for its ID and calls
 * again with ClientID set.
 */
export function SignInWithBrowser(req: $models.BrowserSignInRequest): $CancellablePromise<$models.AddedSite> {
    return $Call.ByID(2285960917, req);
}

/**
 * Validate checks a site name and URL as typed.
 */
export function Validate(name: string, rawURL: string): $CancellablePromise<$models.Validation> {
    return $Call.ByID(2938294759, name, rawURL);
}
